# code:61 == /
bind = SUPER SHIFT, code:61, exec, ~/.config/hypr/showkeys

bind = SUPER CONTROL, Q, exit 
bind = SUPER CONTROL, w, exec, fish -c waybar-wrapper
bind = SUPER, Q, killactive
bind = SUPER SHIFT, F, fullscreen, 0 
bind = SUPER, space, togglefloating
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

bind = SUPER, Return,   exec,   kitty
bind = alt, space,  exec,   fish -c rofi-wrapper
bind = alt, e,  exec,   thunar
bind = alt, b,  exec,   brave-browser
bind = alt, s,  exec,   steam
bind = alt, l,  exec,   lutris
bind = alt, k,  exec,   keepassxc
bind = alt, r,  exec,   rhythmbox
bind = alt, m,  exec,   /opt/Mullvad\ VPN/mullvad-gui
bind = alt, p,  exec,   pavucontrol
bind = alt, q,  exec,   qbittorrent

bind = SUPER alt, z,    exec,   fish -c dm-hub
bind = SUPER alt, l,    exec,   fish -c dm-logout
bind = SUPER alt, o,    exec,   fish -c dm-url-open
bind = SUPER alt, s,    exec,   fish -c wlsunset-wrapper

bind = , code:107, exec, grim ~/Pictures/Screenshots/$(date +'%s_grim.png') # code:107 == Print button
bind = SHIFT, code:107, exec, grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +'%s_grim.png') # code:107 == Print button

bind = SUPER, code:20, togglespecialworkspace, scratch # code:20 == '-'
bind = SUPER SHIFT, code:20, movetoworkspace, special:scratch # code:20 == '-'

# Switch workspaces with SUPER + [0-9]
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

# Scroll through existing workspaces with SUPER + scroll
bind = SUPER, mouse_up,     workspace, e+1
bind = SUPER, mouse_down,   workspace, e-1

bind = SUPER SHIFT, mouse_up,   movetoworkspace, e+1
bind = SUPER SHIFT, mouse_down, movetoworkspace, e-1

bind = SUPER, u, workspace, e+1
bind = SUPER, i, workspace, e-1

bind = SUPER SHIFT, u, movetoworkspace, e+1
bind = SUPER SHIFT, i, movetoworkspace, e-1

# Move active window to a workspace with SUPER + SHIFT + [0-9]
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

# Move focus with SUPER + (hjkl)
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

# Move the windows around (hjkl)
bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, J, movewindow, d
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, L, movewindow, r


bind = , XF86AudioRaiseVolume,  exec, swayosd-client --output-volume raise
bind = , XF86AudioLowerVolume,  exec, swayosd-client --output-volume lower
bind = , XF86AudioMute,         exec, swayosd-client --output-volume mute-toggle
bind = , XF86AudioMicMute,      exec, swayosd-client --input-volume mute-toggle

bind = , XF86AudioPlay,         exec, swayosd-client --playerctl play-pause
bind = , XF86AudioStop,         exec, swayosd-client --playerctl stop
bind = , XF86AudioPrev,         exec, swayosd-client --playerctl previous
bind = , XF86AudioNext,         exec, swayosd-client --playerctl next

bind = , XF86MonBrightnessUp,   exec, swayosd-client --brightness lower
bind = , XF86MonBrightnessDown, exec, swayosd-client --brightness raise"; }
