#! /bin/sh

killall polybar
polybar left &
polybar center &
polybar right &
#polybar top &
#polybar top-compact &

killall sxhkd
sxhkd &

# sets workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width              2
bspc config focused_border_color      "#BD93F9"
bspc config normal_border_color       "#282A36"
bspc config active_border_color	      "#FF5555"
bspc config presel_feedback_color	    "#6272A4"
bspc config urgent_border_color       "#F1FA8C"

bspc config window_gap           20
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a "qimgv" state=fullscreen 
bspc rule -a "steam" desktop='^5'
#bspc rule -a "qBittorrent" desktop='^10'

# autostart
~/.config/bspwm/autostart.sh
